baseURL: "https://runzhou.github.io/blog/" 
languageCode: "en-us"
title: "Shel'Blog"
theme: "PaperMod"

homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

socialIcons: # optional
    - name: "<platform>"
        url: "<link>"
    - name: "<platform 2>"
        url: "<link2>"
